# Kafka cluster with KRaft mode (no ZooKeeper)
# Strimzi Kafka cluster using KafkaNodePool CRDs
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controllers
  namespace: kraft-kafka
  labels:
    strimzi.io/cluster: kraft-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      # IMPORTANT: Specify your StorageClass name below or ensure default StorageClass exists
      # class: standard  # Uncomment and set your StorageClass name
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: brokers
  namespace: kraft-kafka
  labels:
    strimzi.io/cluster: kraft-kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      # IMPORTANT: Specify your StorageClass name below or ensure default StorageClass exists
      # class: standard  # Uncomment and set your StorageClass name
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kraft-kafka-cluster
  namespace: kraft-kafka
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV0
    config:
      # General configuration
      num.partitions: 3
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
