{{- range .Values.kafkaTopics }}
{{- if .enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.nameOverride }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  {{- if .config }}
  config:
    {{- toYaml .config | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
