{{- range .Values.kafkaUsers }}
{{- if .enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.nameOverride }}
spec:
  authentication:
    type: {{ .authentication }}
  {{- if .authorization.enabled }}
  authorization:
    type: {{ .authorization.type }}
    acls:
{{- range .authorization.acls }}
      - resource:
          type: {{ .resource.type }}
{{- if .resource.name }}
          name: {{ .resource.name }}
{{- end }}
          patternType: {{ .resource.patternType }}
{{- if .operations }}
        operations:
{{ toYaml .operations | indent 10 }}
{{- end }}
{{- if .host }}
        host: {{ .host }}
{{- end }}
{{- end }}
  {{- end }}
{{- end }}
{{- end }}
